services:
  email_api:
    image: ghcr.io/dvvtech/email-platform:latest    
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod          
    networks:
      - public-network5
    secrets:
      - SmtpConfig__Username
      - SmtpConfig__Password
      - GoogleRecaptcha__SecretKeyForOxfordAp
      - GoogleRecaptcha__SecretKeyForYashelCenter
      - GoogleRecaptcha__SecretKeyForPingmetasks      
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:   
        - "traefik.enable=true"      
        - "traefik.http.routers.email-api.rule=Host(`api.cloud-platform.pro`) && PathPrefix(`/email`)"      
        - "traefik.http.routers.email-api.entrypoints=websecure"      
        - "traefik.http.routers.email-api.tls.certresolver=letsencrypt"     
        - "traefik.http.services.email-api.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.email-stripprefix.stripprefix.prefixes=/email"
        - "traefik.http.routers.email-api.middlewares=email-stripprefix"

networks:
  public-network5:
    external: true

secrets:
  SmtpConfig__Username:
    external: true
  SmtpConfig__Password:
    external: true
  GoogleRecaptcha__SecretKeyForOxfordAp:
    external: true
  GoogleRecaptcha__SecretKeyForYashelCenter:
    external: true
  GoogleRecaptcha__SecretKeyForPingmetasks:
    external: true